gbm_core_FILES = \
	main/backend.c \
	main/backend.h \
	main/common_drm.h \
	main/gbm.c \
	main/gbm.h \
	main/gbmint.h

gbm_dri_FILES = \
	backends/dri/gbm_dri.c \
	backends/dri/gbm_driint.h

gbm_wrap_FILES = \
	backends/wrap/gbm_wrap.c \
	backends/wrap/gbm_wrap_impl.h
